# Generated by Django 3.2.6 on 2021-08-02 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investimento', models.TextField(max_length=255)),
                ('valor', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('data', models.DateField(default=datetime.datetime(2021, 8, 2, 12, 48, 33, 22084))),
		('autor_musica', models.TextField(max_length=144)),
		('autor_livro', models.TextField(max_length=144)),
		('ano_livro', models.DateField(default=datetime.datetime(2021, 8, 2, 12, 48 , 33, 22084))),
            ],
        ),
    ]
