# Generated by Django 3.2.6 on 2021-08-02 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 2, 12, 54, 38, 625950)),
        ),
    ]
