# Generated by Django 3.2.6 on 2021-08-04 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invista_me', '0004_auto_20210804_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='perdido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 8, 4, 18, 26, 7, 630239)),
        ),
    ]
